### ISSUE TITLE
QUESTION: KMCP merge

### ISSUE THREAD

**Issue by alienzj** [shenwei356/kmcp#14]
Dear Dr Shen,

Thank you for developing so great tool !
I have a question, could you please help me to figure out it ?
You mentioned in your paper that KMCP can automatically merge profiles generated by searching reads on multi small database, does it work at different types of databases ? For example, can it  merge bacteria, archaea, fungi, virus and plasmid profile ?

Thanks!

**Comment by shenwei356** [comment]
Hi Jie, thanks for using KMCP.

It merges *search results* ( not profiles) from multiple databases. https://bioinf.shenwei.me/kmcp/usage/#merge

Check the workflow



![](https://raw.githubusercontent.com/shenwei356/kmcp/main/kmcp-workflow.jpg)



> does it work at different types of databases ? For example, can it merge bacteria, archaea, fungi, virus and plasmid 

Yes, it does.

**Comment by alienzj** [comment]
Understood, thanks !

**Comment by alienzj** [comment]
Dear Dr. Shen,
now quantpi support KMCP.
https://github.com/ohmeta/quantpi/commit/0cf75f382cc20f28fc53433bab950e26e75924b9
This way I can easily use KMCP in my daily work. :smile:

**Comment by alienzj** [comment]
Thank you for the very detailed documentation.
