### ISSUE TITLE
compiling/installing from source

### ISSUE THREAD

**Issue by jianshu93** [shenwei356/kmcp#17]
Hello Wei,

Any guidance to install/compiling from source? I have an aarch64 (or ARM) CPU cluster and need to compile from source. None of the binaries works.

Thanks,

Jianshu

**Comment by shenwei356** [comment]
Sorry, one of my dependencies, [pand](https://github.com/shenwei356/pand), does not support ARM right now.

**Comment by shenwei356** [comment]
Use this first:

- [kmcp_linux_arm64.tar.gz](https://github.com/shenwei356/kmcp/files/8954598/kmcp_linux_arm64.tar.gz)
- [kmcp_darwin_arm64.tar.gz](https://github.com/shenwei356/kmcp/files/8954621/kmcp_darwin_arm64.tar.gz)

But note that the arm64 version has a slower searching speed for databases created with more than one hash function.

    kmcp index -h
      -n, --num-hash int                 ► Number of hash functions in bloom filters. (default 1)

**Comment by shenwei356** [comment]
#### Method 3: Compile from source

1. [Install go](https://go.dev/doc/install)

        wget https://go.dev/dl/go1.17.11.linux-amd64.tar.gz

        tar -zxf go1.17.11.linux-amd64.tar.gz -C $HOME/

        # or 
        #   echo "export PATH=$PATH:$HOME/go/bin" >> ~/.bashrc
        #   source ~/.bashrc
        export PATH=$PATH:$HOME/go/bin

2. Compile KMCP

        # ------------- the latest stable version -------------

        go get -v -u github.com/shenwei356/kmcp/kmcp

        # The executable binary file is located in:
        #   ~/go/bin/kmcp
        # You can also move it to anywhere in the $PATH
        mkdir -p $HOME/bin
        cp ~/go/bin/kmcp $HOME/bin/


        # --------------- the devlopment version --------------
        
        git clone https://github.com/shenwei356/kmcp
        cd kmcp/kmcp/
        go build

        # The executable binary file is located in:
        #   ./kmcp
        # You can also move it to anywhere in the $PATH
        mkdir -p $HOME/bin
        cp ./kmcp $HOME/bin/

**Comment by jianshu93** [comment]
Hello Wei,

I am following the same step to build database in the usage page but use k=16 for gtdb v207, and then f=0.1 but I got a huge database file (30+G) compare to your r202 which is very small (1.5G), I did not expect that there will be such huge difference:


kmcp compute -I all -O gtdb-r207-k16-n10 -k 16 -n 10 -l 100 -B plasmid --log gtdb-r207-k16-n10.log -j 24 --force


time kmcp index -j 24 -I gtdb-r207-k16-n10 -O gtdb.r207.minhash.kmcp -n 1 -f 0.1 --log gtdb.r207.minhash.kmcp.log

Is that because smaller smaller false positive rate or k?


Thanks,

Jianshu

**Comment by shenwei356** [comment]
I guess you were following the[ database building steps for metagenomic profiling](https://bioinf.shenwei.me/kmcp/database/#gtdb). For genome similarity estimation, you need to [compute the sketches](https://bioinf.shenwei.me/kmcp/tutorial/searching/#step-1-building-databases_1).

For example, the `gtdb.minhash.kmcp.tar.gz` of 1.5G was created with FracMinHash/Scaled MinHash (scale = 1000). So the database size was very small. Besides, the reference genomes should not be split (`-n, --split-number`).

**Comment by jianshu93** [comment]
Hello Wei,

Thanks for the suggestion and I have solved it.  An interesting finding: FracMinHash or COBS is very sensitive to different genome size. I am attaching a genome that I know the answer for the best hits in GTDB r207 ranked by Average nucleotide indentity (ANI, calculated by fastANI: https://github.com/ParBLiSS/FastANI) after comparing this genome with all the genomes in GTDB (very expensive, it takes days with more than 100 24 threads compute nodes). When ANI is above 95% it is consistent but not below 95% (fastANI ANI is accurate down to 75% ANI). This important because in a lot of cases, your query genomes may not have a best larger than 95% ANI in the database but say 80% or so, you still need to find this best hit.

Any idea how to bench mark FracMinhash or Syncmer based distance with ANI (how well they are correlated)? By the way, ANI is the standard method to compare to genomes, even MASH was benchmarked against ANI.

Thanks,

Jianshu

**Comment by jianshu93** [comment]
Yes. I was talking about the second best hit，third et. al until hit around 80% ANI. Those hits and their rank should be the same with fastANI best hits.

If you check the one around 80% ANI，it is not the same at all with MASH. Mash correlates very good with ANI with top 10% recall nearly 100%.

Jianshu
