### ISSUE TITLE
0.8.3: Fails on i386: 1 << 32 - 1 (untyped int constant 4294967295) overflows int

### ISSUE THREAD

**Issue by yurivict** [shenwei356/kmcp#19]
```
# github.com/shenwei356/kmcp/kmcp/cmd
kmcp/cmd/compute.go:287:14: 1 << 32 - 1 (untyped int constant 4294967295) overflows int
kmcp/cmd/compute.go:294:19: 1 << 32 - 1 (untyped int constant 4294967295) overflows int
kmcp/cmd/compute.go:300:17: 1 << 32 - 1 (untyped int constant 4294967295) overflows int
*** Error code 2
```

Should ```1<<32-1``` be ```uint64(1)<<32-1```?

FreeBSD 13.1

**Comment by shenwei356** [comment]
Sorry, I should have tested it. Please use the new flag: [v0.8.3.1](https://github.com/shenwei356/kmcp/releases/tag/v0.8.3.1).

**Comment by yurivict** [comment]
Unfortunately Golang doesn't support version numbers with 4 numbers, see https://github.com/golang/go/issues/54515#issuecomment-1219134438

**Comment by shenwei356** [comment]
Please try the [v0.8.4](https://github.com/shenwei356/kmcp/releases/tag/v0.8.4)

**Comment by yurivict** [comment]
Thanks!
