### ISSUE TITLE
Read-level output format

### ISSUE THREAD

**Issue by sjaenick** [shenwei356/kmcp#3]
Hi,

this looks pretty interesting - would it be possible to implement an additional output format
that provides read-level assignments instead of the summary tax. profiles? I.e. maybe something
similar to the default Kraken/Kraken2 output format described at

https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#standard-kraken-output-format

, with either taxids (for NCBI) or maybe complete lineages for other taxonomies (GTDB etc)?

**Comment by shenwei356** [comment]
It did, check the [`kmcp profile` usage](http://bioinf.shenwei.me/kmcp/usage/#profile)

    -B, --binning-result string         ► Save extra binning result in CAMI report.


And  [example output](http://bioinf.shenwei.me/kmcp/tutorial/profiling/#profiling-result-formats):

```
# This is the bioboxes.org binning output format at
# https://github.com/bioboxes/rfc/tree/master/data-format
@Version:0.10.0
@SampleID:
@@SEQUENCEID    TAXID
NC_000913.3_sliding:1244941-1245090     511145
NC_013654.1_sliding:344871-345020       562
NC_000913.3_sliding:3801041-3801190     511145
NC_013654.1_sliding:752751-752900       562
NC_000913.3_sliding:4080871-4081020     562
NC_000913.3_sliding:3588091-3588240     511145
NC_000913.3_sliding:2249621-2249770     562
NC_013654.1_sliding:2080171-2080320     431946
NC_000913.3_sliding:2354841-2354990     511145
NC_013654.1_sliding:437671-437820       431946

```
