### ISSUE TITLE
How to specify multiple kmer values

### ISSUE THREAD

**Issue by mbhall88** [shenwei356/kmcp#30]
In the docs for `compute` it says 
```
  -k, --kmer ints                 ► K-mer size(s). (default [21])
```

I tried `-k 15 21` but that didn't work. How should multiple values be delimited?

**Comment by shenwei356** [comment]
It 's comma-delimited,

    -k  15,21

Or setting multiple times

    -k 15 -k 21

**Comment by mbhall88** [comment]
Ahhh I see. Thanks! Maybe add an example to the docs (and a comment in the `--help`)?
