### ISSUE TITLE
KMCP's MetaPhlAn output doesn't follow the MetaPhlAn file format

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/kmcp#34]
The MetaPhlAn output generated by KMCP is not the same as the one generated by MetaPhlAn. In the KMCP output, the taxid column only contains the taxid of the lowest taxonomic rank (e.g. `1224`), while the one generated by MetaPhlAn contains the full lineage, separated by `|` (e.g. `2|1224`).

<s>This makes the KMCP output incompatible with [TAXPASTA](https://github.com/taxprofiler/taxpasta).</s> Actually, the TAXPASTA error is due to rank not summing up to 100% (due to lineages genomes skipping some ranks).

**Comment by shenwei356** [comment]
Thanks for reporting this. I did not notice this for such a long time ...

- [kmcp_linux_amd64.tar.gz](https://github.com/shenwei356/kmcp/files/11863894/kmcp_linux_amd64.tar.gz)

> Actually, the TAXPASTA error is due to rank not summing up to 100% (due to lineages genomes skipping some ranks).

Skipping ranks should not cause that. Can you attach a file?

Another way is using [taxonkit cami-filter](https://bioinf.shenwei.me/taxonkit/usage/#cami-filter) (without setting `-t, --taxids `) to recompute the abundance in CAMI format, which is one of the input formats of taxpasta.

**Comment by apcamargo** [comment]
Sure! TAXPASTA filed in the step it checks the composition, specifically, at the part it checks if all taxa within a given rank sum up to 100%. I summed up the abundances manually and I saw that some ranks had summed abundances lower than that.

[ERR7569999.metaphlan.txt](https://github.com/shenwei356/kmcp/files/11870366/ERR7569999.metaphlan.txt)
[ERR7569998.metaphlan.txt](https://github.com/shenwei356/kmcp/files/11870367/ERR7569998.metaphlan.txt)
[ERR7569997.metaphlan.txt](https://github.com/shenwei356/kmcp/files/11870368/ERR7569997.metaphlan.txt)

**Comment by shenwei356** [comment]
I see. Some genomes' lineages do not have all the 7 ranks. I have to think about it.

```
for r in k p c o f g s; do
    \ echo -n "$r ";
     cat ERR7569997.metaphlan.txt  \
        | csvtk grep -H -r -p "${r}__[^\|]+$" \
        | csvtk summary -Ht -f 3:sum; \
done

k 100.00
p 85.88
c 68.43
o 55.63
f 41.11
g 19.43
s 100.00

k__Bacteria|p__Bacillota|s__Firmicutes bacterium UBA1422	1947935	0.038769	
k__Bacteria|p__Pseudomonadota|c__Betaproteobacteria|o__Burkholderiales|s__Burkholderiales bacterium	1891238	0.038604
```
