### ISSUE TITLE
strain level profiling?

### ISSUE THREAD

**Issue by zwh82** [shenwei356/kmcp#51]
If I add strain information to nodes.dmp and names.dmp, can kmcp perform strain level profiling?

Thanks.

**Comment by shenwei356** [comment]
It could add '--level stain' if you have multiple reference genomes with strain-level taxids for each species.

**Comment by zwh82** [comment]
Sorry, I found that the specific strain composition in the sample can be known from the `ref` column in `*.kmcp.profile`.
