### ISSUE TITLE
A minor issue on console messages

### ISSUE THREAD

**Issue by zhanxw** [shenwei356/kmcp#8]
Thanks for developing this tool.

When I inputted an empty file, the console outputs:
...
11:27:03.868 [WARN] no invalid sequences in file: input.fq.gz
...

The text should be "no valid sequences" instead of "no invalid sequences"?

**Comment by shenwei356** [comment]
Oh, you're right! Thanks for reporting this.

**Comment by zhanxw** [comment]
Another minor issue in the console message. 

Here are some console messages for  `kmcp search`:

...
23:44:29.502 [INFO] -------------------- [main parameters] --------------------
23:44:29.502 [INFO]   minimum    query length: 30
23:44:29.502 [INFO]   minimum  matched k-mers: 10
23:44:29.502 [INFO]   minimum  query coverage: 0.550000
23:44:29.505 [INFO]   minimum target coverage: 0.000000
23:44:29.505 [INFO]   minimum target coverage: 0.000000
23:44:29.505 [INFO] -------------------- [main parameters] --------------------
...


There are duplicated information on `minimum target coverage`. Not sure if it is intended.

**Comment by shenwei356** [comment]
Thank you again!
